import { Footer } from "@/components/layout/Footer";
import { Header } from "@/components/layout/Header";
import { MobileBottomMenu } from "@/components/layout/MobileBottomMenu";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ShopLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <div className="flex min-h-0 flex-1 flex-col pb-[calc(4rem+env(safe-area-inset-bottom))] md:pb-0">
        <Header />
        <main className="mx-auto w-full max-w-7xl flex-1 px-6 pt-10">
          {children}
        </main>
        <Footer />
      </div>

      <MobileBottomMenu />
    </>
  );
}
