
import { Footer } from "@/components/layout/Footer";
import { Header } from "@/components/layout/Header";
import { MobileBottomMenu } from "@/components/layout/MobileBottomMenu";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ShopLayout({ children }: LayoutProps<"/">) {
  return (
    <>
      <Header />
      <main className="mx-auto max-w-7xl px-6 pt-10">
        {children}
      </main>
      <Footer />

      <MobileBottomMenu />
    </>
  );
}
